version: '3.8'

services:
  db:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Aici încărcăm scriptul care creează tabelele automat la prima pornire
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    ports:
      - "5002:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src 

volumes:
  postgres_data:
